name: amd64_macos_gcc

on: [push]

permissions:
  contents: write

jobs:
  amd64_macos_gcc:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install deps
      run: |
        brew update
        brew install pkg-config sdl12-compat

    - run: make

    - name: Get version
      id: version
      run: |
        output=$(build-mac/femto8 --version | head -n 1)
        if [ -z "$output" ]; then output="build-${GITHUB_SHA:0:7}"; fi
        echo "result=$output" >> "$GITHUB_OUTPUT"

    - name: Stage README/LICENSE into build dir
      run: cp README.md LICENSE build-mac/

    - name: Compress Files
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: build-mac
        files: |
          README.md
          LICENSE
          femto8
        outPath: build-mac/femto8_Darwin_amd64.tar.gz

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build-mac/femto8_Darwin_amd64.tar.gz

    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build-mac/femto8_Darwin_amd64.tar.gz
        tag: ${{ steps.version.outputs.result }}
        overwrite: true
